package co.com.samtel.enumeraciones;

public enum TableMigration {
	
	BIG_RECOGIDOS,BIG_RECUPERA_CARTERA_CASTIGADA,BIG_CIUDADES,BIG_BARRIOS,BIG_CODIGOS_ABOGADO,BIG_TIPO_IDENT_CLIENTES,
	BIG_ACTIVIDAD_ECONOMICA_INTERNA,BIG_TIPO_TRANSACCION
}
